# Series

- 1차원 배열 위에서 아래로 출력 -> idx: 데이터

In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.arange(13, 20)
# print(arr)
# print('-' * 25)
s = pd.Series(arr)
# print(s)

In [3]:
#형변환 가능
s = pd.Series(arr, dtype='int32')
# print(s)

## indexing
- series[인덱스번호]
- series[문자] (index='문자')

In [4]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)

In [5]:
s[2]

'park'

In [6]:
# s = pd.Series(person, index=['a', 'b', 'c', 'd'])
s = pd.Series(person, index=list('abcd'))

In [7]:
s['a']

'kim'

## NaN(Not a Number) 결측치

In [8]:
s = pd.Series(person + [np.nan]) # nan값 추가
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [9]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


## Fancy indexing

In [11]:
f = ['바나나', np.nan, '사과', '복숭아', '포도']
s = pd.Series(f, index=(list('가나다라마')))
print(s)

가    바나나
나    NaN
다     사과
라    복숭아
마     포도
dtype: object


In [12]:
s[['다', '가']]

다     사과
가    바나나
dtype: object

In [13]:
s.iloc[[2,3]]

다     사과
라    복숭아
dtype: object

## bool

In [14]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마     포도
dtype: object

In [15]:
a = [True, False, False, True, True]
s[a]

가    바나나
라    복숭아
마     포도
dtype: object

In [17]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int32


In [18]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

## 결측치(NaN) 처리 

In [19]:
s = pd.Series([1, 2, 3, np.nan, 3, 4, 9, np.nan, 4, 7])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
4    3.0
5    4.0
6    9.0
7    NaN
8    4.0
9    7.0
dtype: float64


In [21]:
# 시리즈 목록에서 null인 데이터 목록 출력
s.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [23]:
s[s.isnull()]

3   NaN
7   NaN
dtype: float64

In [24]:
s.isna()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

In [25]:
# 시리즈 목록에서 결측치 제외 데이터 
s.notnull()

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
8     True
9     True
dtype: bool

# DataFrame

In [28]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
df = pd.DataFrame(arr)
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [31]:
df = pd.DataFrame(arr, columns=['가', '나', '다'], index=['a', 'b', 'c'])
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [32]:
data = {
    'name': ['kim', 'lee', 'hong'],
    'age': [10, 29, 30],
    'location': ['seoul', 'LA', 'tokyo']
}
df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   29       LA
2  hong   30    tokyo

In [33]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [34]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [35]:
df.values

array([['kim', 10, 'seoul'],
       ['lee', 29, 'LA'],
       ['hong', 30, 'tokyo']], dtype=object)

In [36]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [37]:
df.T

0    1      2
name        kim  lee   hong
age          10   29     30
location  seoul   LA  tokyo

In [38]:
df['name']

0     kim
1     lee
2    hong
Name: name, dtype: object

In [39]:
df[['name', 'location']]

name location
0   kim    seoul
1   lee       LA
2  hong    tokyo

In [40]:
df.rename(columns={'location': 'hometown'}, inplace=True)

In [41]:
df

name  age hometown
0   kim   10    seoul
1   lee   29       LA
2  hong   30    tokyo